import React,{useEffect,useMemo}from"react";
import{ArrowLeft,Users,Sparkles}from"lucide-react";
import{useI18n}from"../../lib/LangContext";import{useMarketplace}from"../../context/MarketplaceContext";
import{isPublicCatalogProduct}from"../../lib/cloud/catalog.js";import{creatorPath,productPath,publicUrl}from"../../lib/acquisition.js";
import{trackAcquisition,trackSiteEvent}from"../../lib/acquisitionTrack.js";import{updatePageSEO,getDefaultSEO}from"../../lib/seo.js";import ShareBar from"./ShareBar";
export default function CreatorAcquisition({category=null,navigate}){const{lang}=useI18n(),L=(h,e)=>lang==="he"?h:e,{products,marketers}=useMarketplace(),real=useMemo(()=>(products||[]).filter(p=>isPublicCatalogProduct(p,marketers)),[products,marketers]),creators=useMemo(()=>{const ids=new Set(real.map(p=>p.marketerId));return(marketers||[]).filter(m=>m?.id&&ids.has(m.id)&&(!category||real.some(p=>p.marketerId===m.id&&p.category===category)))},[real,marketers,category]),path=category?`/creators/${encodeURIComponent(category)}`:"/creators";
useEffect(()=>{trackSiteEvent("creator_landing_view",{page:path});updatePageSEO({...getDefaultSEO("home"),title:category?`יוצרי ${category} | לייקלינק`:"יוצרים וקהילת LikeLink2 | לייקלינק",description:"יוצרים,מוצרים וסיפורים אמיתיים עם attribution ברור.",url:publicUrl(path),jsonLd:{"@context":"https://schema.org","@type":"CollectionPage",name:category||"LikeLink creators",url:publicUrl(path)}});return()=>updatePageSEO(getDefaultSEO("home"))},[path,category]);
const studio=()=>{trackAcquisition("creator_cta_click","פתחת Studio מעמוד היוצרים",{page:path});trackSiteEvent("studio_opened",{page:path});navigate("/studio")};
return <div dir="rtl" className="min-h-screen" style={{background:"var(--bg)",color:"var(--text)"}}><div className="mx-auto max-w-5xl px-4 py-6 pb-24"><button onClick={()=>navigate("/")} className="tap mb-6 flex gap-2 text-sm"><ArrowLeft size={16}/>{L("חזרה לגילוי","Back to discovery")}</button><header className="rounded-3xl p-6 md:p-10" style={{background:"linear-gradient(135deg,rgba(108,76,241,.28),rgba(20,25,54,.92))",border:"1px solid var(--border)"}}><p className="mb-3 flex gap-2 text-xs"><Sparkles size={14} color="var(--accent)"/>{L("קהילת היוצרים","Creator community")}</p><h1 className="text-3xl md:text-5xl font-bold">{L("יש לך קהל? הפוך אותו להכנסה מתוכן ומוצרים","Have an audience? Turn it into content and commerce")}</h1><p className="mt-4 text-sm opacity-75">{L("גלו, צרו, פרסמו ומדדו לפי כללי התוכנית האמיתיים. כל מוצר וקליק מקבלים ייחוס ברור.","Discover, create, publish and measure under the real program rules. Every product and click keeps attribution.")}</p><button onClick={studio} data-testid="creator-cta" className="tap mt-6 rounded-xl px-5 py-3 font-bold" style={{background:"var(--accent)",color:"#fff"}}>{L("פתח Studio","Open Studio")}</button></header><section className="mt-8"><h2 className="text-2xl font-bold">{L("יוצרים שאפשר לגלות","Creators worth discovering")}</h2>{creators.length?<div className="mt-4 grid gap-4 sm:grid-cols-2">{creators.map(m=>{const owned=real.filter(p=>p.marketerId===m.id);return <article key={m.id} className="rounded-2xl p-5" style={{background:"var(--bg-subtle)",border:"1px solid var(--border)"}}><h3 className="font-bold">{m.name}</h3><p className="text-xs opacity-65">{owned.length} {L("מוצרים","products")}</p><div className="mt-4 flex gap-2"><a href={creatorPath(m.slug||m.id)} className="tap rounded-lg px-3 py-2 text-xs" style={{background:"var(--accent)",color:"#fff"}}>{L("פתח פרופיל","Open profile")}</a>{owned[0]&&<a href={productPath(owned[0].id)} className="tap rounded-lg px-3 py-2 text-xs" style={{background:"var(--bg-elevated)"}}>{L("פתח מוצר","Open product")}</a>}</div><ShareBar compact path={creatorPath(m.slug||m.id)} title={m.name} text={L("גלו את הפרופיל","Discover this profile")} marketerId={m.id}/></article>})}</div>:<div className="mt-4 rounded-2xl p-8 text-center" style={{background:"var(--bg-subtle)",border:"1px solid var(--border)"}}><Users className="mx-auto mb-3 opacity-60"/><h3 className="font-bold">{L("אין כאן עדיין יוצרים מאושרים","No approved creators yet")}</h3><p className="mt-2 text-sm opacity-70">{L("העמוד יתמלא רק ממידע אמיתי ומאושר.","This page will fill only from real approved data.")}</p></div>}</section><div className="mt-8"><ShareBar path={path} title={L("גלו את היוצרים בלייקלינק","Discover LikeLink creators")} text={L("פרופילים, מוצרים ומדידה אמיתית","Profiles, products and real measurement")} compact/></div></div></div>}
